// frontend/src/components/ChatRoomSidebar.tsx
import { useState, useEffect, useCallback } from 'react'
import api from '@/utils/api'
import type { ChatRoom } from '@/types'

interface Props {
  currentRoomId: string
  onSelectRoom: (roomId: string) => void
}

const COLORS = ['#6366f1','#3b82f6','#06b6d4','#10b981','#84cc16','#eab308','#f97316','#ef4444','#ec4899','#8b5cf6']
const DEFAULT_ROOMS: ChatRoom[] = [
  { id: 'general', name: '일반', participantCount: 0, createdAt: '', color: '#6366f1' },
  { id: 'tech', name: '기술 토론', participantCount: 0, createdAt: '', color: '#10b981' },
  { id: 'random', name: '자유 토론', participantCount: 0, createdAt: '', color: '#f97316' }
]

export default function ChatRoomSidebar({ currentRoomId, onSelectRoom }: Props) {
  const [rooms, setRooms] = useState<ChatRoom[]>([])
  const [showCreate, setShowCreate] = useState(false)
  const [name, setName] = useState('')
  const [desc, setDesc] = useState('')
  const [color, setColor] = useState(COLORS[0])
  const [creating, setCreating] = useState(false)

  const fetchRooms = useCallback(async () => {
    try {
      const res = await api.get('/api/chat/rooms')
      setRooms(res.data.data || res.data || [])
    } catch {
      setRooms(DEFAULT_ROOMS)
    }
  }, [])

  useEffect(() => { fetchRooms() }, [fetchRooms])

  const handleCreate = async () => {
    if (name.trim().length < 2 || creating) return
    setCreating(true)
    try {
      const res = await api.post('/api/chat/rooms', { name: name.trim(), description: desc, color })
      const created = res.data.data || res.data
      setRooms(prev => [created, ...prev])
      onSelectRoom(created.id)
      setShowCreate(false)
      setName(''); setDesc(''); setColor(COLORS[0])
    } catch { /* */ }
    finally { setCreating(false) }
  }

  return (
    <div className="d-flex flex-column h-100" style={{ background: 'var(--bs-body-bg)', minWidth: 240 }}>
      <div className="p-3 border-bottom">
        <h6 className="mb-0"><i className="bi bi-chat-dots me-2" />채팅방</h6>
      </div>

      <div className="flex-grow-1 overflow-auto">
        {rooms.map(room => (
          <div key={room.id} className={`p-3 border-bottom d-flex align-items-center gap-2 ${currentRoomId === room.id ? 'bg-primary text-white' : ''}`}
            style={{ cursor: 'pointer' }} onClick={() => onSelectRoom(room.id)}>
            <span className="rounded-circle flex-shrink-0" style={{ width: 12, height: 12, background: room.color || '#6366f1' }} />
            <div className="flex-grow-1 text-truncate">
              <div className="fw-semibold" style={{ fontSize: '0.9rem' }}>{room.name}</div>
              <small className={currentRoomId === room.id ? 'text-white-50' : 'text-muted'}>{room.participantCount || 0}명{room.maxParticipants ? `/${room.maxParticipants}` : ''}</small>
            </div>
          </div>
        ))}
      </div>

      <div className="p-3 border-top">
        <button className="btn btn-primary w-100" onClick={() => setShowCreate(true)}>
          <i className="bi bi-plus-circle me-2" />새 채팅방
        </button>
      </div>

      {showCreate && (
        <div className="position-fixed top-0 start-0 w-100 h-100 d-flex align-items-center justify-content-center" style={{ background: 'rgba(0,0,0,0.5)', zIndex: 2000 }} onClick={() => setShowCreate(false)}>
          <div className="card shadow-lg" style={{ maxWidth: 420, width: '100%', margin: 16 }} onClick={e => e.stopPropagation()}>
            <div className="card-header bg-primary text-white d-flex justify-content-between align-items-center">
              <strong>새 채팅방 만들기</strong>
              <button className="btn-close btn-close-white" onClick={() => setShowCreate(false)} />
            </div>
            <div className="card-body">
              <div className="mb-3">
                <label className="form-label small fw-semibold">채팅방 이름</label>
                <input className="form-control" value={name} onChange={e => setName(e.target.value)} placeholder="이름 (2글자 이상)" maxLength={50} autoFocus />
              </div>
              <div className="mb-3">
                <label className="form-label small fw-semibold">설명 (선택)</label>
                <textarea className="form-control" value={desc} onChange={e => setDesc(e.target.value)} rows={2} maxLength={200} />
              </div>
              <div className="mb-3">
                <label className="form-label small fw-semibold">색상</label>
                <div className="d-flex gap-2 flex-wrap">
                  {COLORS.map(c => (
                    <div key={c} className="rounded-circle d-flex align-items-center justify-content-center" onClick={() => setColor(c)}
                      style={{ width: 32, height: 32, background: c, cursor: 'pointer', border: color === c ? '3px solid #333' : '3px solid transparent', color: 'white' }}>
                      {color === c && <i className="bi bi-check" />}
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div className="card-footer d-flex gap-2 justify-content-end">
              <button className="btn btn-secondary" onClick={() => setShowCreate(false)}>취소</button>
              <button className="btn btn-primary" disabled={name.trim().length < 2 || creating} onClick={handleCreate}>
                {creating ? <span className="spinner-border spinner-border-sm" /> : '생성'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/components/ChatRoomSidebar.vue
<template>
  <div class="chat-room-sidebar h-100 d-flex flex-column">
    <div class="sidebar-header p-3 border-bottom">
      <h6 class="mb-0">
        <i class="bi bi-chat-dots me-2"></i>
        채팅방
      </h6>
    </div>

    <div class="room-list flex-grow-1 overflow-auto">
      <!-- 로딩 상태 -->
      <div v-if="loading" class="text-center py-4">
        <div class="spinner-border spinner-border-sm text-primary" role="status"></div>
        <small class="text-muted ms-2">채팅방 불러오는 중...</small>
      </div>

      <!-- 에러 상태 -->
      <div v-else-if="error" class="text-center py-4 px-3">
        <i class="bi bi-exclamation-triangle text-warning" style="font-size: 2rem;"></i>
        <p class="text-muted mt-2 mb-2 small">채팅방 목록을 불러올 수 없습니다.</p>
        <button class="btn btn-sm btn-outline-primary" @click="fetchRooms">다시 시도</button>
      </div>

      <!-- 빈 상태 -->
      <div v-else-if="rooms.length === 0" class="text-center py-4 px-3">
        <i class="bi bi-chat-dots text-muted" style="font-size: 2rem;"></i>
        <p class="text-muted mt-2 small">채팅방이 없습니다. 새로 만들어보세요!</p>
      </div>

      <!-- 채팅방 목록 -->
      <div
        v-for="room in rooms"
        :key="room.id"
        class="room-item p-3 border-bottom cursor-pointer"
        :class="{ active: selectedRoom === room.id }"
        @click="selectRoom(room.id)"
      >
        <div class="d-flex justify-content-between align-items-center">
          <div class="room-info">
            <div class="room-color-indicator" :style="{ backgroundColor: room.color }"></div>
            <div>
              <div class="fw-semibold room-name">{{ room.name }}</div>
              <small class="text-muted">{{ room.participantCount || 0 }}명 참여중</small>
            </div>
          </div>
          <div class="room-status">
            <span class="badge bg-success rounded-pill">{{ room.participantCount || 0 }}</span>
            <i v-if="room.isPrivate" class="bi bi-lock-fill ms-1 text-muted" title="비공개 채팅방"></i>
          </div>
        </div>
      </div>
    </div>

    <div class="sidebar-footer p-3 border-top">
      <button class="btn btn-create-room w-100" @click="showCreateModal = true">
        <i class="bi bi-plus-circle me-2"></i>
        새 채팅방 만들기
      </button>
    </div>

    <!-- Create Room Modal -->
    <CreateRoomModal
      v-model="showCreateModal"
      @room-created="handleRoomCreated"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import api from '@/utils/api'
import type { ChatRoom } from '@/types'
import CreateRoomModal from './CreateRoomModal.vue'

interface CreateRoomData {
  name: string
  description: string
  color: string
  isPrivate: boolean
  allowInvites: boolean
}

interface Props {
  selectedRoom: string
}

const props = defineProps<Props>()
const emit = defineEmits<{
  'room-selected': [roomId: string]
  'update:selected-room': [roomId: string]
}>()

const showCreateModal = ref(false)
const rooms = ref<ChatRoom[]>([])
const loading = ref(false)
const error = ref(false)

const fetchRooms = async () => {
  loading.value = true
  error.value = false
  try {
    const response = await api.get('/api/chat/rooms')
    const data = response.data
    rooms.value = data.data || data || []
  } catch (e) {
    console.error('채팅방 목록 로드 실패:', e)
    error.value = true
    // 백엔드 미연결 시 기본 채팅방 제공
    rooms.value = [
      { id: 'general', name: '일반', participantCount: 0, createdAt: '', color: '#6366f1', isPrivate: false },
      { id: 'tech', name: '기술 토론', participantCount: 0, createdAt: '', color: '#10b981', isPrivate: false },
      { id: 'random', name: '자유 토론', participantCount: 0, createdAt: '', color: '#f97316', isPrivate: false }
    ]
    error.value = false
  } finally {
    loading.value = false
  }
}

const selectRoom = (roomId: string) => {
  emit('update:selected-room', roomId)
  emit('room-selected', roomId)
}

const handleRoomCreated = async (roomData: CreateRoomData) => {
  try {
    const response = await api.post('/api/chat/rooms', {
      name: roomData.name,
      description: roomData.description,
      color: roomData.color,
      isPrivate: roomData.isPrivate,
      allowInvites: roomData.allowInvites
    })
    const created = response.data.data || response.data
    rooms.value.unshift(created)
    selectRoom(created.id)
  } catch (e) {
    console.error('채팅방 생성 실패:', e)
    // 로컬 폴백
    const newRoom: ChatRoom = {
      id: `room_${Date.now()}`,
      name: roomData.name,
      participantCount: 1,
      createdAt: new Date().toISOString(),
      color: roomData.color,
      isPrivate: roomData.isPrivate,
      description: roomData.description,
      allowInvites: roomData.allowInvites
    }
    rooms.value.unshift(newRoom)
    selectRoom(newRoom.id)
  }
}

onMounted(() => {
  fetchRooms()
})
</script>

<style scoped>
.chat-room-sidebar {
  background-color: var(--bs-body-bg);
  min-width: 280px;
}

.room-item {
  transition: all 0.2s ease;
  cursor: pointer;
  position: relative;
}

.room-item:hover {
  background-color: var(--bs-light);
  transform: translateX(2px);
}

.room-item.active {
  background-color: var(--bs-primary);
  color: white;
}

.room-item.active .text-muted {
  color: rgba(255, 255, 255, 0.7) !important;
}

.room-info {
  display: flex;
  align-items: center;
  gap: 12px;
  flex: 1;
}

.room-color-indicator {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  flex-shrink: 0;
  border: 2px solid rgba(255, 255, 255, 0.3);
}

.room-item.active .room-color-indicator {
  border-color: rgba(255, 255, 255, 0.6);
}

.room-name {
  font-size: 15px;
  line-height: 1.3;
}

.btn-create-room {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border: none;
  color: white;
  padding: 12px 16px;
  border-radius: 12px;
  font-weight: 600;
  transition: all 0.3s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  overflow: hidden;
}

.btn-create-room:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.4);
  color: white;
}

.btn-create-room:active {
  transform: translateY(0);
}

.btn-create-room::before {
  content: '';
  position: absolute;
  top: 50%;
  left: 50%;
  width: 0;
  height: 0;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 50%;
  transform: translate(-50%, -50%);
  transition: width 0.3s ease, height 0.3s ease;
}

.btn-create-room:hover::before {
  width: 300px;
  height: 300px;
}

.sidebar-header {
  background: linear-gradient(135deg, #f8f9ff 0%, #e8f0fe 100%);
}

.sidebar-footer {
  background: linear-gradient(135deg, #f8f9ff 0%, #e8f0fe 100%);
}

[data-bs-theme="dark"] .room-item:hover {
  background-color: var(--bs-dark);
}

[data-bs-theme="dark"] .sidebar-header,
[data-bs-theme="dark"] .sidebar-footer {
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
}
</style>
